name: Tabs counter

on:
  pull_request:
    branches:
      - main

jobs:
  find-changed-files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.changed-files.outputs.all_changed_files }}
    name: Get changed-files
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v13.1

  create-logs:
    name: Log tabs count
    runs-on: ubuntu-latest
    needs: find-changed-files
    strategy:
      matrix:
        changed-files: ${{ needs.find-changed-files.outputs.files }}
    steps:
      - name: List all changed files
        run: |
          echo "${{ matrix.changed-files }} was changed" > ${{ matrix.changed-files }}.log 
          cat "${{ matrix.changed-files }} | grep -P "\t" > ${{ matrix.changed-files }}.log 2>&1
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.changed-files }}.log
