name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          echo "List of changed files got succesfully"
          echo "${{ steps.files.outputs.all }}"  

      - name: List all changed files
        run: |
          for file in ${{ steps.files.outputs.all }}; do
            echo "$file was changed"  >> ${file}.log
          done

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: ${file}.log