name: Tabs counter

on:
  pull_request:
    branches:
      - main

jobs:
  find-changed-files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.files.outputs.all }}
    name: Get changed-files
    steps:
      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

  create-logs:
    name: Log tabs count
    runs-on: ubuntu-latest
    needs: find-changed-files
    strategy:
      matrix:
        changed-files: ${{fromJson(needs.find-changed-files.outputs.files)}}
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: List all changed files
        run: |
          echo "${{ matrix.changed-files }} was changed" >> ${{ matrix.changed-files }}.log 2>&1
          echo "Tabs count:" >> ${{ matrix.changed-files }}.log 2>&1
          awk '{ print gsub (/\t/,"")}' ${{ matrix.changed-files }} | awk '{ i+=$1 } END { print i }'>> ${{ matrix.changed-files }}.log 2>&1

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.changed-files }}.log
